env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:jest-dom/recommended
  - plugin:react-hooks/recommended
  - plugin:testing-library/react
  - plugin:@typescript-eslint/recommended
  - prettier
  - react-app
ignorePatterns: ['**/dist/**']
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
  quotes:
    - error
    - single
  semi:
    - error
    - always
  @typescript-eslint/no-empty-function:
    - off
  import/no-anonymous-default-export:
    - off
